kafka-lag-exporter {
  port = 8000
  poll-interval = 30 seconds
  lookup-table-size = 1000
  client-group-id = "kafkalagexporter"
  kafka-client-timeout = 10 seconds

  clusters = [
    {
      name = "nyc-taxi-cluster"
      bootstrap-brokers = "kafka:9092"
      group-whitelist = [".*"]
      group-blacklist = []
      topic-whitelist = ["nyc_taxi_events"]
      consumer-properties = {}
      admin-client-properties = {}
      labels = {}
    }
  ]
}

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
}
