apiVersion: 1

datasources:
  - name: BigData-API
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://metrics-api:8000
    isDefault: true
    jsonData:
      tlsSkipVerify: true
    version: 1
    editable: true
